import fs from 'fs';
import path from 'path';
import os from 'os';
import { spawnSync } from 'child_process';
import type { SkillRecord } from '../skill-loader';

const AUTO_MARKER = '<!-- auto-generated by neuroclaw skills:sync - edits will be overwritten. -->';
const ANTIGRAVITY_MARKER = '<!-- auto-generated by neuroclaw skills:sync - edits will be overwritten. Add custom Antigravity instructions to ANTIGRAVITY.local.md instead. -->';

function firstLine(file: string): string {
  try {
    return fs.readFileSync(file, 'utf-8').split(/\r?\n/, 1)[0] ?? '';
  } catch {
    return '';
  }
}

function hasAntigravityBinary(): boolean {
  const result = spawnSync('which', ['antigravity'], { encoding: 'utf-8' });
  return result.status === 0 && !!result.stdout.trim();
}

function safeFileName(name: string): string {
  const safe = name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
  return safe || 'skill';
}

function renderSkill(skill: SkillRecord): string {
  const lines = [
    AUTO_MARKER,
    `# ${skill.name}`,
    '',
    skill.description ? `Description: ${skill.description}` : '',
    `Source: ${skill.source}${skill.plugin ? ` (${skill.plugin})` : ''}`,
    skill.triggers.length ? `Triggers: ${skill.triggers.join(', ')}` : '',
    skill.tools.length   ? `Tools: ${skill.tools.join(', ')}` : '',
    skill.scripts.length ? `Scripts: ${skill.scripts.join(', ')}` : '',
    '',
    skill.body.trim(),
    '',
  ].filter(line => line !== '');
  return lines.join('\n');
}

function renderIndex(skills: SkillRecord[]): string {
  const lines = [
    AUTO_MARKER,
    '# NeuroClaw Skills',
    '',
    'Antigravity agents can use these mirrored NeuroClaw skills. Use the skill body as task-specific guidance, and use NeuroClaw MCP tools such as list_skills and run_skill_script when a script-backed skill needs execution.',
    '',
  ];
  for (const skill of skills) {
    const file = `${safeFileName(skill.name)}.md`;
    lines.push(`- ${skill.name}: ${skill.description || 'No description'} (${skill.source}) -> ${file}`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderAntigravityMd(skills: SkillRecord[], localAppendix: string): string {
  const lines = [
    ANTIGRAVITY_MARKER,
    '# NeuroClaw Skill Index',
    '',
    'Antigravity should treat `.config/antigravity/skills/` as the local skill catalog mirrored from NeuroClaw. Each entry below points to the full skill instructions.',
    '',
  ];
  for (const skill of skills) {
    const file = `.config/antigravity/skills/${safeFileName(skill.name)}.md`;
    lines.push(`- ${skill.name}: ${skill.description || 'No description'} (${file})`);
  }
  if (localAppendix.trim()) {
    lines.push('', '## Local Instructions', '', localAppendix.trim(), '');
  } else {
    lines.push('');
  }
  return lines.join('\n');
}

function removeStaleGeneratedSkillFiles(dir: string, keep: Set<string>): void {
  if (!fs.existsSync(dir)) return;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!ent.isFile() || !ent.name.endsWith('.md') || keep.has(ent.name)) continue;
    const file = path.join(dir, ent.name);
    if (firstLine(file) === AUTO_MARKER) fs.unlinkSync(file);
  }
}

export interface AntigravitySkillExportResult {
  written: string[];
  skipped: string[];
}

export async function isAntigravitySkillExportAvailable(repoRoot = process.cwd()): Promise<boolean> {
  const antigravityMdPath = path.join(repoRoot, 'ANTIGRAVITY.md');
  return (
    hasAntigravityBinary() ||
    fs.existsSync(path.join(os.homedir(), '.config', 'antigravity')) ||
    firstLine(antigravityMdPath) === ANTIGRAVITY_MARKER
  );
}

export async function exportAntigravitySkills(
  skills: SkillRecord[],
  repoRoot = process.cwd(),
): Promise<AntigravitySkillExportResult> {
  const written: string[] = [];
  const skipped: string[] = [];

  if (!(await isAntigravitySkillExportAvailable(repoRoot))) {
    return { written, skipped: ['antigravity not detected and no .config/antigravity workspace present'] };
  }

  const antigravityDir = path.join(repoRoot, '.config', 'antigravity');
  const skillsDir = path.join(antigravityDir, 'skills');
  fs.mkdirSync(skillsDir, { recursive: true });

  const keep = new Set<string>(['INDEX.md']);
  for (const skill of skills) {
    const filename = `${safeFileName(skill.name)}.md`;
    keep.add(filename);
    const target = path.join(skillsDir, filename);
    const body = renderSkill(skill);
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf-8') !== body) {
      fs.writeFileSync(target, body, 'utf-8');
      written.push(path.relative(repoRoot, target));
    }
  }

  const indexPath = path.join(skillsDir, 'INDEX.md');
  const indexBody = renderIndex(skills);
  if (!fs.existsSync(indexPath) || fs.readFileSync(indexPath, 'utf-8') !== indexBody) {
    fs.writeFileSync(indexPath, indexBody, 'utf-8');
    written.push(path.relative(repoRoot, indexPath));
  }

  removeStaleGeneratedSkillFiles(skillsDir, keep);

  const antigravityMdPath = path.join(repoRoot, 'ANTIGRAVITY.md');
  const localAppendixPath = path.join(repoRoot, 'ANTIGRAVITY.local.md');
  const antigravityMdBody = renderAntigravityMd(
    skills,
    fs.existsSync(localAppendixPath) ? fs.readFileSync(localAppendixPath, 'utf-8') : '',
  );
  const existingFirstLine = firstLine(antigravityMdPath);
  if (!fs.existsSync(antigravityMdPath) || existingFirstLine === ANTIGRAVITY_MARKER) {
    if (!fs.existsSync(antigravityMdPath) || fs.readFileSync(antigravityMdPath, 'utf-8') !== antigravityMdBody) {
      fs.writeFileSync(antigravityMdPath, antigravityMdBody, 'utf-8');
      written.push(path.relative(repoRoot, antigravityMdPath));
    }
  } else {
    skipped.push('ANTIGRAVITY.md exists and was not generated by skills:sync; left it unchanged');
  }

  return { written, skipped };
}
