import fs from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';
import type { SkillRecord } from '../skill-loader';

const AUTO_MARKER = '<!-- auto-generated by neuroclaw skills:sync - edits will be overwritten. -->';
const AGENTS_MARKER = '<!-- auto-generated by neuroclaw skills:sync - edits will be overwritten. Add custom Codex instructions to AGENTS.local.md instead. -->';

function firstLine(file: string): string {
  try {
    return fs.readFileSync(file, 'utf-8').split(/\r?\n/, 1)[0] ?? '';
  } catch {
    return '';
  }
}

function hasCodexBinary(): boolean {
  const result = spawnSync('which', ['codex'], { encoding: 'utf-8' });
  return result.status === 0 && !!result.stdout.trim();
}

function safeFileName(name: string): string {
  const safe = name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
  return safe || 'skill';
}

function renderSkill(skill: SkillRecord): string {
  const lines = [
    AUTO_MARKER,
    `# ${skill.name}`,
    '',
    skill.description ? `Description: ${skill.description}` : '',
    `Source: ${skill.source}${skill.plugin ? ` (${skill.plugin})` : ''}`,
    skill.triggers.length ? `Triggers: ${skill.triggers.join(', ')}` : '',
    skill.tools.length ? `Tools: ${skill.tools.join(', ')}` : '',
    skill.scripts.length ? `Scripts: ${skill.scripts.join(', ')}` : '',
    '',
    skill.body.trim(),
    '',
  ].filter(line => line !== '');
  return lines.join('\n');
}

function renderIndex(skills: SkillRecord[]): string {
  const lines = [
    AUTO_MARKER,
    '# NeuroClaw Skills',
    '',
    'Codex agents can use these mirrored NeuroClaw skills. Use the skill body as task-specific guidance, and use NeuroClaw MCP tools such as list_skills and run_skill_script when a script-backed skill needs execution.',
    '',
  ];
  for (const skill of skills) {
    const file = `${safeFileName(skill.name)}.md`;
    lines.push(`- ${skill.name}: ${skill.description || 'No description'} (${skill.source}) -> ${file}`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderAgentsIndex(skills: SkillRecord[], localAppendix: string): string {
  const lines = [
    AGENTS_MARKER,
    '# NeuroClaw Skill Index',
    '',
    'Codex should treat `.codex/skills/` as the local skill catalog mirrored from NeuroClaw. Each entry below points to the full skill instructions.',
    '',
  ];
  for (const skill of skills) {
    const file = `.codex/skills/${safeFileName(skill.name)}.md`;
    lines.push(`- ${skill.name}: ${skill.description || 'No description'} (${file})`);
  }
  if (localAppendix.trim()) {
    lines.push('', '## Local Instructions', '', localAppendix.trim(), '');
  } else {
    lines.push('');
  }
  return lines.join('\n');
}

function removeStaleGeneratedSkillFiles(dir: string, keep: Set<string>): void {
  if (!fs.existsSync(dir)) return;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!ent.isFile() || !ent.name.endsWith('.md') || keep.has(ent.name)) continue;
    const file = path.join(dir, ent.name);
    if (firstLine(file) === AUTO_MARKER) fs.unlinkSync(file);
  }
}

export interface CodexSkillExportResult {
  written: string[];
  skipped: string[];
}

export async function isCodexSkillExportAvailable(repoRoot = process.cwd()): Promise<boolean> {
  const agentsPath = path.join(repoRoot, 'AGENTS.md');
  return hasCodexBinary() || fs.existsSync(path.join(repoRoot, '.codex')) || firstLine(agentsPath) === AGENTS_MARKER;
}

export async function exportCodexSkills(skills: SkillRecord[], repoRoot = process.cwd()): Promise<CodexSkillExportResult> {
  const written: string[] = [];
  const skipped: string[] = [];
  if (!(await isCodexSkillExportAvailable(repoRoot))) {
    return { written, skipped: ['codex not detected and no .codex workspace present'] };
  }

  const codexDir = path.join(repoRoot, '.codex');
  const skillsDir = path.join(codexDir, 'skills');
  fs.mkdirSync(skillsDir, { recursive: true });

  const keep = new Set<string>(['INDEX.md']);
  for (const skill of skills) {
    const filename = `${safeFileName(skill.name)}.md`;
    keep.add(filename);
    const target = path.join(skillsDir, filename);
    const body = renderSkill(skill);
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf-8') !== body) {
      fs.writeFileSync(target, body, 'utf-8');
      written.push(path.relative(repoRoot, target));
    }
  }

  const indexPath = path.join(skillsDir, 'INDEX.md');
  const indexBody = renderIndex(skills);
  if (!fs.existsSync(indexPath) || fs.readFileSync(indexPath, 'utf-8') !== indexBody) {
    fs.writeFileSync(indexPath, indexBody, 'utf-8');
    written.push(path.relative(repoRoot, indexPath));
  }

  removeStaleGeneratedSkillFiles(skillsDir, keep);

  const agentsPath = path.join(repoRoot, 'AGENTS.md');
  const agentsBody = renderAgentsIndex(skills, fs.existsSync(path.join(repoRoot, 'AGENTS.local.md')) ? fs.readFileSync(path.join(repoRoot, 'AGENTS.local.md'), 'utf-8') : '');
  const existingFirstLine = firstLine(agentsPath);
  if (!fs.existsSync(agentsPath) || existingFirstLine === AGENTS_MARKER) {
    if (!fs.existsSync(agentsPath) || fs.readFileSync(agentsPath, 'utf-8') !== agentsBody) {
      fs.writeFileSync(agentsPath, agentsBody, 'utf-8');
      written.push(path.relative(repoRoot, agentsPath));
    }
  } else {
    skipped.push('AGENTS.md exists and was not generated by skills:sync; left it unchanged');
  }

  return { written, skipped };
}
