-- ============================================================================
-- NeuroClaw Knowledge Base — glossary extension
-- Target: self-hosted Supabase (supabase.neurolearninglabs.com), neuroclaw_kb schema
-- Backs Furina's (Localization & Translation) approved per-locale terminology
-- lookup so re-runs converge on the SAME "approved" translation for a given
-- source term instead of re-deriving it differently each time.
--
-- Idempotent: safe to re-run. Depends on kb-schema.sql having already created
-- the neuroclaw_kb schema + service_role grants.
-- ============================================================================

set search_path to neuroclaw_kb, public, extensions;

create table if not exists neuroclaw_kb.kb_glossary (
  id              bigint generated by default as identity primary key,
  source_term     text not null,
  -- Case/whitespace-normalized lookup key, generated so app code never has to
  -- keep it in sync. Plain (non-expression) column ⇒ usable as an upsert
  -- on_conflict target via PostgREST.
  source_term_key text generated always as (lower(trim(source_term))) stored,
  source_locale   text not null default 'en',
  target_locale   text not null,
  translation     text not null,
  notes           text,
  status          text not null default 'approved'
                    check (status in ('approved', 'draft', 'deprecated')),
  updated_by      text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),
  unique (source_term_key, source_locale, target_locale)
);

create index if not exists kb_glossary_target_locale_idx
  on neuroclaw_kb.kb_glossary (target_locale);

-- ── Privileges (mirrors kb-schema.sql) ───────────────────────────────────────
grant all on neuroclaw_kb.kb_glossary to service_role;
grant all on all sequences in schema neuroclaw_kb to service_role;
