-- ============================================================================
-- NeuroClaw Knowledge Base — schema migration
-- Target: self-hosted Supabase (supabase.neurolearninglabs.com)
-- Creates the dedicated `neuroclaw_kb` schema, tables, match RPCs,
-- service_role grants, and indexes. Idempotent: safe to re-run.
--
-- Ordering note: tables → functions → GRANTS → indexes. Functions and grants
-- run BEFORE the vector indexes so that even if the vector index fails (e.g.
-- pgvector < 0.5.0 has no HNSW), the KB is still fully usable (writes + search
-- work without an ANN index — the <=> operator falls back to a sequential scan).
-- The vector indexes are wrapped in non-fatal DO blocks (HNSW → ivfflat → skip).
--
-- AFTER running this, expose the schema to the API:
--   add `neuroclaw_kb` to PGRST_DB_SCHEMAS  (e.g. public,storage,graphql_public,neuroclaw_kb)
--   then restart PostgREST:  docker compose restart rest
-- Without that step every PostgREST call returns PGRST106 "schema must be one of…".
-- ============================================================================

create schema if not exists neuroclaw_kb;
create extension if not exists vector with schema extensions;

-- vector resolves from public/extensions; tables/functions land in neuroclaw_kb.
set search_path to neuroclaw_kb, public, extensions;

-- ── Tables ──────────────────────────────────────────────────────────────────

create table if not exists neuroclaw_kb.kb_sources (
  source_id   text primary key,
  title       text,
  summary     text,
  total_words integer     default 0,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create table if not exists neuroclaw_kb.kb_pages (
  id                    bigint generated by default as identity primary key,
  source_id             text not null references neuroclaw_kb.kb_sources(source_id) on delete cascade,
  url                   text not null,
  chunk_number          integer not null,
  content               text not null,
  metadata              jsonb default '{}'::jsonb,
  embedding             vector(1536),
  content_search_vector tsvector generated always as (to_tsvector('english', content)) stored,
  created_at            timestamptz default now(),
  unique (url, chunk_number)
);

create table if not exists neuroclaw_kb.kb_code_examples (
  id           bigint generated by default as identity primary key,
  source_id    text not null references neuroclaw_kb.kb_sources(source_id) on delete cascade,
  url          text not null,
  chunk_number integer not null,
  content      text not null,
  summary      text,
  metadata     jsonb default '{}'::jsonb,
  embedding    vector(1536),
  created_at   timestamptz default now(),
  unique (url, chunk_number)
);

-- ── Match RPCs (called via supabase-js .rpc with db.schema = neuroclaw_kb) ────
-- Table refs are schema-qualified so resolution never depends on runtime search_path.

create or replace function neuroclaw_kb.match_pages(
  query_embedding vector(1536),
  match_count     int  default 5,
  filter_source   text default null
) returns table (
  id           bigint,
  source_id    text,
  url          text,
  chunk_number int,
  content      text,
  metadata     jsonb,
  similarity   float
) language plpgsql stable as $$
begin
  return query
  select p.id, p.source_id, p.url, p.chunk_number, p.content, p.metadata,
         1 - (p.embedding operator(extensions.<=>) query_embedding) as similarity
  from neuroclaw_kb.kb_pages p
  where p.embedding is not null
    and (filter_source is null or p.source_id = filter_source)
  order by p.embedding operator(extensions.<=>) query_embedding
  limit match_count;
end;
$$;

create or replace function neuroclaw_kb.match_code_examples(
  query_embedding vector(1536),
  match_count     int  default 5,
  filter_source   text default null
) returns table (
  id           bigint,
  source_id    text,
  url          text,
  chunk_number int,
  content      text,
  summary      text,
  metadata     jsonb,
  similarity   float
) language plpgsql stable as $$
begin
  return query
  select c.id, c.source_id, c.url, c.chunk_number, c.content, c.summary, c.metadata,
         1 - (c.embedding operator(extensions.<=>) query_embedding) as similarity
  from neuroclaw_kb.kb_code_examples c
  where c.embedding is not null
    and (filter_source is null or c.source_id = filter_source)
  order by c.embedding operator(extensions.<=>) query_embedding
  limit match_count;
end;
$$;

-- ── Privileges (self-hosted service_role must use + read/write + execute) ─────
-- Run BEFORE the indexes so a vector-index failure can't leave the role
-- read-only (PostgREST returns 404, not 403, when a role can't write a table).

grant usage on schema neuroclaw_kb to service_role;
grant all on all tables    in schema neuroclaw_kb to service_role;
grant all on all sequences in schema neuroclaw_kb to service_role;
grant execute on all functions in schema neuroclaw_kb to service_role;

alter default privileges in schema neuroclaw_kb grant all on tables to service_role;
alter default privileges in schema neuroclaw_kb grant all on sequences to service_role;
alter default privileges in schema neuroclaw_kb grant execute on functions to service_role;

-- ── Plain indexes (work on any PostgreSQL) ───────────────────────────────────

create index if not exists kb_pages_fts_idx
  on neuroclaw_kb.kb_pages using gin (content_search_vector);

create index if not exists kb_pages_source_idx
  on neuroclaw_kb.kb_pages (source_id);

create index if not exists kb_code_source_idx
  on neuroclaw_kb.kb_code_examples (source_id);

-- ── Vector ANN indexes (best-effort, non-fatal) ──────────────────────────────
-- HNSW needs pgvector >= 0.5.0; ivfflat needs >= 0.4.0. If neither is available
-- the index is skipped — search still works via a sequential scan (fine for a
-- small/starting KB). Each block catches its own error so the migration always
-- completes (functions + grants above are already applied at this point).

do $$
begin
  begin
    create index if not exists kb_pages_embedding_idx
      on neuroclaw_kb.kb_pages using hnsw (embedding vector_cosine_ops)
      with (m = 16, ef_construction = 64);
    raise notice 'kb: kb_pages HNSW index created';
  exception when others then
    raise notice 'kb: HNSW on kb_pages unavailable (%) — trying ivfflat', sqlerrm;
    begin
      create index if not exists kb_pages_embedding_idx
        on neuroclaw_kb.kb_pages using ivfflat (embedding vector_cosine_ops) with (lists = 100);
      raise notice 'kb: kb_pages ivfflat index created';
    exception when others then
      raise notice 'kb: no vector index on kb_pages (%) — search uses seq scan', sqlerrm;
    end;
  end;
end $$;

do $$
begin
  begin
    create index if not exists kb_code_embedding_idx
      on neuroclaw_kb.kb_code_examples using hnsw (embedding vector_cosine_ops)
      with (m = 16, ef_construction = 64);
    raise notice 'kb: kb_code_examples HNSW index created';
  exception when others then
    raise notice 'kb: HNSW on kb_code_examples unavailable (%) — trying ivfflat', sqlerrm;
    begin
      create index if not exists kb_code_embedding_idx
        on neuroclaw_kb.kb_code_examples using ivfflat (embedding vector_cosine_ops) with (lists = 100);
      raise notice 'kb: kb_code_examples ivfflat index created';
    exception when others then
      raise notice 'kb: no vector index on kb_code_examples (%) — search uses seq scan', sqlerrm;
    end;
  end;
end $$;
